version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: influenciai_postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: influenciai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: influenciai_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: influenciai_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:

